# -*- coding: utf-8 -*-
"""Practice_Sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbeqNs9VtEex1_f99esK1ZzzLnjP4klA

PSet 1
Create a to-do list containing your daily To-dos using either a list or a tuple
Perform some operations to get a particular day to-do one after the other, and add the operation that shows all your to-dos for the days accordingly
"""

#The to_do list is created
Mon = "Monday: Get to work"
Tue = "Tuesday: Attend programming class"
Wed = "Wednesday: Go to the gym"
Thur = "Thursday: Work from home"
Fri = "Friday: Spend a latenight outside"
Sat = "Saturday: Play football and do laundry"
Sun = "Sunday: Go to church and prepare for work"

#The to_do list is unpacked
to_do = [Mon, Tue, Wed, Thur, Fri, Sat, Sun]
mon_routine, tue_routine, wed_routine, thur_routine, fri_routine, sat_routine, sun_routine = to_do
print(wed_routine)

#I added an extra day and used an iteration to print the whole to_do list
extra_day = "Extra_day: See a movie"
to_do.append(extra_day)
for schedule in to_do:
  print (schedule)

"""
PSet 2
Create a dictionary that contains your basic bio info, which must have properties of skills which is a list of your skills

"""

#I created a dictionary here containing some basic info and my skills
my_bio = {
    "Name":"Anthony",
    "Age":"23",
    "Nationality":"Nigerian",
    "Skill_1":"Graphics Design",
    "Skill_2":"Programming",
    "Skill_3":"Photography"

}

"""
Loop through your bio dictionary and print the keys and values to stdout, for skills
Make skills as a heading and print out all the skills out

"""

# Here the keys and values in the dictionary are printed to stdout
for key,value in my_bio.items():
  print(f"My {key} is {value}")

skills = [my_bio["Skill_1"], my_bio["Skill_2"], my_bio["Skill_3"]]
for skillsets in skills:
  print(f"My skillsets include {skillsets}")

"""
Use a lambda expression to double each items in list of range 1-50 using list comprehnsion

"""

operation= [(lambda x: x**2)(x) for x in range(1,51)]
print(operation)